#!/usr/bin/env python3
"""Export Jarvis's AI-generated sprite frames as an SD-card RGB565 sprite pack.

Mirrors export_openclaw_lab.py's structure (full independent blink frames,
no patch-diffing, since SD has no flash-partition budget to optimize
against), merging Jarvis's two source manifests (idle directions +
expressions) into the canonical thirteen-track layout.
"""
import hashlib
import json
from pathlib import Path

from export_sprite_firmware import BlockStore, display_pixels, read_png, rgb565, write_if_changed

ROOT = Path(__file__).resolve().parents[1]
DIRECTION_SOURCE = ROOT / "web/generated-sprites-jarvis"
EXPRESSION_SOURCE = ROOT / "web/generated-expressions-jarvis"
OUTPUT = ROOT / "assets/jarvis-lab.bin"
METADATA = ROOT / "assets/jarvis-lab.json"
HEADER = ROOT / "firmware/Copilot/generated/jarvis_assets.h"
TRACKS = (
    "right", "left", "up", "down", "up_right", "up_left", "down_right", "down_left",
    "surprise", "working", "complete", "attention", "attention_alternate",
)
DIRECTION_TRACKS = frozenset((
    "right", "left", "up", "down", "up_right", "up_left", "down_right", "down_left",
))
STEPS = 24
BLINKS = 5


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main():
    direction_manifest = json.loads((DIRECTION_SOURCE / "animation.json").read_text())
    expression_manifest = json.loads((EXPRESSION_SOURCE / "animation.json").read_text())
    for manifest, label in ((direction_manifest, "direction"), (expression_manifest, "expression")):
        if (manifest.get("width"), manifest.get("height"), manifest.get("count")) != (240, 224, STEPS):
            raise ValueError(f"Jarvis {label} manifest has invalid dimensions or step count.")
    store = BlockStore(ROOT / "build/jarvis-compression")
    packed_frames = []
    png_hashes = {}
    for track in TRACKS:
        source = DIRECTION_SOURCE if track in DIRECTION_TRACKS else EXPRESSION_SOURCE
        manifest = direction_manifest if track in DIRECTION_TRACKS else expression_manifest
        frames = manifest["directions"].get(track, {}).get("frames")
        if not isinstance(frames, list) or len(frames) != STEPS:
            raise ValueError(f"Jarvis track {track} must contain {STEPS} frames.")
        for step, frame in enumerate(frames):
            names = [frame.get("file"), *frame.get("blinks", [])]
            if len(names) != BLINKS:
                raise ValueError(f"Jarvis track {track} frame {step} must contain five blink levels.")
            packed = []
            for name in names:
                path = source / name
                pixels, png_hash = read_png(path, (240, 224))
                png_hashes[f"{track}/{name}"] = png_hash
                packed.append(display_pixels(rgb565(pixels)).tobytes())
            packed_frames.append(packed)
    frame_blocks = [[None] * BLINKS for _ in packed_frames]
    group_ends = []
    # Keep normal open-eye playback contiguous; blink variants are colder data.
    for level in range(BLINKS):
        for index, packed in enumerate(packed_frames):
            frame_blocks[index][level] = store.add(packed[level], 412)
        group_ends.append(len(store.data))
    blocks = [block for frame in frame_blocks for block in frame]
    if len(blocks) != len(TRACKS) * STEPS * BLINKS:
        raise ValueError("Jarvis block count is invalid.")
    write_if_changed(OUTPUT, bytes(store.data))
    lines = [
        "// Generated by tools/export_jarvis_lab.py; do not edit.",
        "#pragma once",
        "#include <cstdint>",
        "namespace copilot {",
        "struct JarvisSpriteBlock { uint32_t offset, size; };",
        f"constexpr uint8_t kJarvisDirections = {len(TRACKS)};",
        f"constexpr uint8_t kJarvisSteps = {STEPS};",
        f"constexpr uint8_t kJarvisBlinkLevels = {BLINKS};",
        f"constexpr uint32_t kJarvisOpenDataSize = {group_ends[0]};",
        f"constexpr uint32_t kJarvisDataSize = {len(store.data)};",
        "constexpr uint8_t kJarvisDataSha256[32] = {",
        "  " + ", ".join(f"0x{byte:02x}" for byte in hashlib.sha256(store.data).digest()) + ",",
        "};",
        f"constexpr JarvisSpriteBlock kJarvisFrames[{len(blocks)}] = {{",
    ]
    lines.extend(f"  {{{block['offset']}, {block['size']}}}," for block in blocks)
    lines.extend(["};", "}  // namespace copilot", ""])
    write_if_changed(HEADER, "\n".join(lines))
    metadata = {
        "formatVersion": 1,
        "encoding": "zlib-rgb565-word-up-be",
        "width": 412, "height": 352, "sourceWidth": 240, "sourceHeight": 224,
        "steps": STEPS, "blinkLevels": [1, .75, .5, .25, 0],
        "directions": list(TRACKS),
        "frameBlocks": len(blocks), "dataBytes": len(store.data),
        "dataSha256": hashlib.sha256(store.data).hexdigest(),
        "uniqueBlocks": len(store.blocks),
        "directionManifestSha256": digest(DIRECTION_SOURCE / "animation.json"),
        "expressionManifestSha256": digest(EXPRESSION_SOURCE / "animation.json"),
        "packExporterSha256": digest(ROOT / "tools/export_jarvis_lab.py"),
        "generatedHeaderSha256": digest(HEADER),
        "referenceSha256": digest(ROOT / "assets/jarvis/reference.png"),
        "sourcePngSha256": png_hashes,
    }
    write_if_changed(METADATA, json.dumps(metadata, indent=2) + "\n")
    print(f"Jarvis sprite pack: {len(store.data):,} bytes, {len(store.blocks)} unique blocks")


if __name__ == "__main__":
    main()
